# Generated by Django 3.2.5 on 2021-07-09 22:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('price_discount', models.PositiveIntegerField(default=0, verbose_name='price discount')),
                ('image', models.ImageField(blank=True, upload_to='pizzas', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='PizzaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pizzas.pizza', verbose_name='pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Pizza rate',
                'verbose_name_plural': 'Pizza rates',
            },
        ),
        migrations.CreateModel(
            name='PizzaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('content', models.TextField(verbose_name='content')),
                ('approved_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='approved time')),
                ('approved_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='approved user')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizzas.pizza', verbose_name='pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Pizza comment',
                'verbose_name_plural': 'Pizza comments',
            },
        ),
        migrations.AddConstraint(
            model_name='pizzarate',
            constraint=models.UniqueConstraint(fields=('user', 'pizza'), name='unique user_pizza_rate'),
        ),
    ]
